# Generated by Django 4.1.7 on 2023-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_verified_owner',
            field=models.BooleanField(default=False, verbose_name='is verified owner'),
        ),
    ]
