# Generated by Django 4.1.7 on 2023-03-17 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='in_date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='out_time',
        ),
        migrations.AddField(
            model_name='reserve',
            name='in_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 21, 22, 20, 738331), verbose_name='in date time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='out_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 21, 22, 34, 985178), verbose_name='out date time'),
            preserve_default=False,
        ),
    ]
